#!/usr/bin/env ruby
# encoding: utf-8

$INITIAL_PWD = Dir.pwd.dup
$EXECUTABLE_PATH = "#{File.expand_path(File.dirname($PROGRAM_NAME))}"

CALLEE   = "#{$EXECUTABLE_PATH}/0x-simple-redirection-test-callee"
LOG_FILE = "#{$EXECUTABLE_PATH}/log.tmp"

if File.exist?(LOG_FILE)
  File.delete(LOG_FILE)
end

system("#{CALLEE}")

File.open(LOG_FILE, "r:utf-8"){|logfile|
#  logfile.flock(File::LOCK_EX)
  $stdout.write(logfile.read)
}

